### PR TITLE
Shimont/voodoo mock support running singletest by name

### PR DESCRIPTION
**Pull request by shimont-lb**
This PR introduce the ability to run single test also by name, as well as by line number.

### CODE REVIEW

**Comment by shimont-lb** [comment]
@shlomimatichin Can u, please, check this out?

**Review by shlomimatichin — CHANGES_REQUESTED** [review]
hi shimon,

first of all, thank you for the PR. happy to hear of new users, let me know what i can do to help. say hello to muli and abel. my feedback is as follows:
Major: When you changed SINGLE_TEST_LINE to IDENTIFIER, you broke the vim integration (which has SINGLE_TEST_LINE appear in the vim script). tip: i personally git grep when making changes of this sort.
Minor: The python script "gettest" is not so clearly written. I would suggest two completely code paths for search by line number or by name regex, since by regex is basically just a regex search on the file, and it avoid some of the qurickiness as when calculating maxLineNumberToCheck.
Style: TEST_IDENTIFIER i would change to REGEX_OR_LINE_NUMBER. otherwise it's yet another new term in the code, but it's not so clear outside the python file what goes there. kinda half way Hungarian notation ;-)

let me know if you are planning on fixing the PR, or you prefer for me to do so.
shabat shalom,
and thanks again,
shlomi

**Comment by shimont-lb** [comment]
Hi @shlomimatichin thanks for the responsiveness. I'll fix it and and resubmit my PR later today.
Thanks for your comments!

**Comment by shimont-lb** [comment]
@shlomimatichin followed your suggestions. Please, review.

**Comment by shimont-lb** [comment]
@shlomimatichin Can u, please review?

**Comment by shimont-lb** [comment]
@shlomimatichin Can u, please review?

**Comment by shimont-lb** [comment]
Thanks @shlomimatichin !

**Pull request merged**
